# Generated by Django 2.2.4 on 2019-08-29 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1', models.CharField(blank=True, choices=[('ARI', 'Arizona Cardinals'), ('ATL', 'Atlanta Falcons'), ('BAL', 'Baltimore Ravens'), ('BUF', 'Buffalo Bills'), ('CAR', 'Carolina Panthers'), ('CHI', 'Chicago Bears'), ('CIN', 'Cincinnati Bengals'), ('CLE', 'Cleveland Browns'), ('DAL', 'Dallas Cowboys'), ('DEN', 'Denver Broncos'), ('DET', 'Detroit Lions'), ('GB', 'Green Bay Packers'), ('HOU', 'Houston Texans'), ('IND', 'Indianapolis Colts'), ('JAX', 'Jacksonville Jaguars'), ('KC', 'Kansas City Chiefs'), ('MIA', 'Miami Dolphins'), ('MIN', 'Minnesota Vikings'), ('NE', 'New England Patriots'), ('NO:', 'New Orleans Saints'), ('NYG', 'New York Giants'), ('NYJ', 'New York Jets'), ('OAK', 'Oakland Raiders'), ('PHI', 'Philadelphia Eagles'), ('PIT', 'Pittsburgh Steelers'), ('SD:', 'San Diego Chargers'), ('SEA', 'Seattle Seahawks'), ('SF', 'San Francisco 49ers'), ('STL', 'Saint Louis Rams'), ('TB', 'Tampa Bay Buccaneers'), ('TEN', 'Tennessee Titans'), ('WAS', 'Washington Redskins')], max_length=3, unique=True)),
                ('team2', models.CharField(blank=True, choices=[('ARI', 'Arizona Cardinals'), ('ATL', 'Atlanta Falcons'), ('BAL', 'Baltimore Ravens'), ('BUF', 'Buffalo Bills'), ('CAR', 'Carolina Panthers'), ('CHI', 'Chicago Bears'), ('CIN', 'Cincinnati Bengals'), ('CLE', 'Cleveland Browns'), ('DAL', 'Dallas Cowboys'), ('DEN', 'Denver Broncos'), ('DET', 'Detroit Lions'), ('GB', 'Green Bay Packers'), ('HOU', 'Houston Texans'), ('IND', 'Indianapolis Colts'), ('JAX', 'Jacksonville Jaguars'), ('KC', 'Kansas City Chiefs'), ('MIA', 'Miami Dolphins'), ('MIN', 'Minnesota Vikings'), ('NE', 'New England Patriots'), ('NO:', 'New Orleans Saints'), ('NYG', 'New York Giants'), ('NYJ', 'New York Jets'), ('OAK', 'Oakland Raiders'), ('PHI', 'Philadelphia Eagles'), ('PIT', 'Pittsburgh Steelers'), ('SD:', 'San Diego Chargers'), ('SEA', 'Seattle Seahawks'), ('SF', 'San Francisco 49ers'), ('STL', 'Saint Louis Rams'), ('TB', 'Tampa Bay Buccaneers'), ('TEN', 'Tennessee Titans'), ('WAS', 'Washington Redskins')], max_length=3, unique=True)),
                ('team3', models.CharField(blank=True, choices=[('ARI', 'Arizona Cardinals'), ('ATL', 'Atlanta Falcons'), ('BAL', 'Baltimore Ravens'), ('BUF', 'Buffalo Bills'), ('CAR', 'Carolina Panthers'), ('CHI', 'Chicago Bears'), ('CIN', 'Cincinnati Bengals'), ('CLE', 'Cleveland Browns'), ('DAL', 'Dallas Cowboys'), ('DEN', 'Denver Broncos'), ('DET', 'Detroit Lions'), ('GB', 'Green Bay Packers'), ('HOU', 'Houston Texans'), ('IND', 'Indianapolis Colts'), ('JAX', 'Jacksonville Jaguars'), ('KC', 'Kansas City Chiefs'), ('MIA', 'Miami Dolphins'), ('MIN', 'Minnesota Vikings'), ('NE', 'New England Patriots'), ('NO:', 'New Orleans Saints'), ('NYG', 'New York Giants'), ('NYJ', 'New York Jets'), ('OAK', 'Oakland Raiders'), ('PHI', 'Philadelphia Eagles'), ('PIT', 'Pittsburgh Steelers'), ('SD:', 'San Diego Chargers'), ('SEA', 'Seattle Seahawks'), ('SF', 'San Francisco 49ers'), ('STL', 'Saint Louis Rams'), ('TB', 'Tampa Bay Buccaneers'), ('TEN', 'Tennessee Titans'), ('WAS', 'Washington Redskins')], max_length=3, unique=True)),
                ('team4', models.CharField(blank=True, choices=[('ARI', 'Arizona Cardinals'), ('ATL', 'Atlanta Falcons'), ('BAL', 'Baltimore Ravens'), ('BUF', 'Buffalo Bills'), ('CAR', 'Carolina Panthers'), ('CHI', 'Chicago Bears'), ('CIN', 'Cincinnati Bengals'), ('CLE', 'Cleveland Browns'), ('DAL', 'Dallas Cowboys'), ('DEN', 'Denver Broncos'), ('DET', 'Detroit Lions'), ('GB', 'Green Bay Packers'), ('HOU', 'Houston Texans'), ('IND', 'Indianapolis Colts'), ('JAX', 'Jacksonville Jaguars'), ('KC', 'Kansas City Chiefs'), ('MIA', 'Miami Dolphins'), ('MIN', 'Minnesota Vikings'), ('NE', 'New England Patriots'), ('NO:', 'New Orleans Saints'), ('NYG', 'New York Giants'), ('NYJ', 'New York Jets'), ('OAK', 'Oakland Raiders'), ('PHI', 'Philadelphia Eagles'), ('PIT', 'Pittsburgh Steelers'), ('SD:', 'San Diego Chargers'), ('SEA', 'Seattle Seahawks'), ('SF', 'San Francisco 49ers'), ('STL', 'Saint Louis Rams'), ('TB', 'Tampa Bay Buccaneers'), ('TEN', 'Tennessee Titans'), ('WAS', 'Washington Redskins')], max_length=3, unique=True)),
                ('manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='teams.Manager')),
            ],
        ),
    ]
